import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#ffffff',
  '--slot4-page-text': '#001e2c',
  '--slot4-panel-bg': '#fafafa',
  '--slot4-surface-bg': '#ffffff',
  '--slot4-muted-text': '#535353',
  '--slot4-soft-muted-text': '#7c7c7c',
  '--slot4-accent': '#fc6736',
  '--slot4-accent-fill': '#fc6736',
  '--slot4-accent-soft': '#fff1eb',
  '--slot4-on-accent': '#ffffff',
  '--slot4-dark-bg': '#001e2c',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#f6f6f6',
  '--slot4-cream': '#ffffff',
  '--slot4-warm': '#fafafa',
  '--slot4-lavender': '#f6f6f6',
  '--slot4-gray': '#fafafa',
  '--slot4-sky': '#e6eff3',
  '--slot4-body-gradient': 'none',
  '--editable-page-bg': '#ffffff',
  '--editable-page-text': '#001e2c',
  '--editable-container': '1240px',
  '--editable-border': 'rgba(14,14,14,0.10)',
  '--editable-nav-bg': '#ffffff',
  '--editable-nav-text': '#001e2c',
  '--editable-nav-active': '#001e2c',
  '--editable-nav-active-text': '#ffffff',
  '--editable-cta-bg': '#001e2c',
  '--editable-cta-text': '#ffffff',
  '--editable-search-bg': '#ffffff',
  '--editable-footer-bg': '#ffffff',
  '--editable-footer-text': '#001e2c',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent-soft)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_1px_2px_rgba(0,30,44,0.04)]',
  shadowStrong: 'shadow-[0_20px_60px_rgba(0,30,44,0.10)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.04),rgba(0,0,0,0.6))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[77.5rem] px-6 md:px-8 lg:px-12',
    sectionY: 'py-16 md:py-20 lg:py-24',
  },
  layout: {
    safeGrid: 'grid gap-6 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start',
  },
  type: {
    eyebrow: 'text-[11px] font-semibold uppercase tracking-[0.24em] text-[var(--slot4-accent)]',
    heroTitle: "editable-display text-[2.75rem] font-bold leading-[1.02] tracking-[-0.04em] sm:text-[3.5rem] lg:text-[4rem]",
    sectionTitle: "editable-display text-[2rem] font-bold leading-[1.15] tracking-[-0.03em] sm:text-[2.5rem] lg:text-[3rem]",
    body: 'text-base leading-relaxed text-[var(--slot4-muted-text)]',
  },
  surface: {
    card: `rounded-2xl border ${editablePalette.border} ${editablePalette.surfaceBg} p-6`,
    soft: `rounded-2xl border ${editablePalette.border} ${editablePalette.panelBg} p-6`,
    dark: `rounded-2xl ${editablePalette.darkBg} ${editablePalette.darkText}`,
  },
  button: {
    primary: `inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--slot4-dark-bg)] px-6 py-3 text-sm font-semibold text-white transition duration-300 hover:-translate-y-0.5 hover:brightness-110`,
    secondary: `inline-flex items-center justify-center gap-2 rounded-lg border border-[var(--editable-border)] bg-white px-6 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:-translate-y-0.5 hover:border-[var(--slot4-page-text)]`,
    accent: `inline-flex items-center justify-center gap-2 rounded-lg bg-[var(--slot4-accent-fill)] px-6 py-3 text-sm font-semibold text-white transition duration-300 hover:-translate-y-0.5 hover:brightness-105`,
  },
  media: {
    frame: `relative overflow-hidden rounded-xl ${editablePalette.mediaBg}`,
    ratio: 'aspect-[3/2]',
  },
  motion: {
    lift: 'transition-transform duration-300 hover:-translate-y-1',
    fade: 'transition duration-300 hover:opacity-80',
  },
} as const

export const aiLayoutRules = [
  'Palette lives in editableRootStyle; every section consumes those CSS variables.',
  'Home structure is centralized in HomeSections.tsx.',
  'Never replace dynamic feeds with mock arrays.',
  'Always use postHref() for post links.',
] as const
